import subprocess
import json
from pathlib import Path


TASKMASTER_CMD = r"C:\Users\aryan\AppData\Roaming\npm\task-master.cmd"
TASKS_JSON_PATH = Path(
    r"C:\Users\aryan\Documents\Code Stuff\neurax\.taskmaster\tasks\tasks.json"
)


def parse_prd(file_path: str):
    """
    Main orchestrator function.
    Runs task-master on the provided PRD file and returns generated tasks.
    """

    run_taskmaster(file_path)

    tasks = load_tasks_json()

    return tasks


def run_taskmaster(prd_path: str) -> None:
    """
    Executes task-master CLI to parse the PRD.
    """

    try:
        subprocess.run(
            [
                TASKMASTER_CMD,
                "parse-prd",
                prd_path,
                "--force"
            ],
            input="\n",
            text=True,
            check=True
        )

    except subprocess.CalledProcessError as e:
        raise RuntimeError(f"Taskmaster execution failed: {e}")


def load_tasks_json() -> dict:
    """
    Loads the tasks.json file generated by task-master.
    """

    if not TASKS_JSON_PATH.exists():
        raise FileNotFoundError("tasks.json was not generated by task-master.")

    with open(TASKS_JSON_PATH, "r", encoding="utf-8") as f:
        return json.load(f)